CMS_HOST: studio.local.overhang.io
CMS_OAUTH2_SECRET: uXtJTTvWqMGCVgZoeMPtkkyG
CONTACT_EMAIL: contact@www.myopenedx.com
DEV_PROJECT_NAME: Project-Occa_Dev
ENABLE_HTTPS: false
ID: Sg3C35g9BUQFt2EtLJLxF2l2
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpQIBAAKCAQEAo6S1acPvJsYgoA9QH26pIKdH0s0Moy1qlAZnEKB2F3jnweVh

  59+CsM/axJ1nW0d8YI+HPyqXCUc71PBk3mPaSXgOx/bQC5h5KSdOxdkj4/FJwD3c

  rquIzLq0RPuu0VdPWGeWJ5MjUMfx1la1EEv0DB8FerR23e4N/Bxg6wWA0FuNY7Zb

  swq95rDURqQ8gZ5esJdnEz8PONQX0Y7NWpupOEUPLGg3HUp+LKoybth6vFAQkjwp

  TbKOb4wBNH8EUPQm21WlZEW669DqFZsV0MSULIwTa+qNrkuY2kasNevVSdkDPgGY

  UjjBPZtSeCerFaLkJy738FhXyUVIkcXD/VyjKQIDAQABAoIBAAOk8eNSmTtYUzat

  UJ/6k2qmPwu7REpIAyUbxWTR5f9c0nB3fsguqpbschdJ2BjozSTLXXwzIxzySKtT

  1TM8rwpO0alzXiu78ArSFMeEL+/uGjHdTtJXAJtqlwQoRLrlwl8aI3ZrKPCuGz0m

  Pi8IOf2hHTqf1TvZBtez/BaPz1AUiLQWWnwpCCENQdMtUii+IeG2cpXcsXz06szq

  qyx+LJ+pVoUhZGzFid+fyo0Rhn/HkOOCLF0468XS98s85+YY21xBnYYmNUWzapeh

  TSbxOvCL1U/Vmec5cslWJPjstyQsgHBL3DsmYX3OAVBwLs2s3+TqZzM+uSwGo74t

  tkM0pEECgYEAt1VsFgldSmBzyizM+ilAC8YjYrivyRV2ZN86VgAW5j5vkL6r3qwU

  ol6hfbg/lvGyiMO48E/gddTOuryHb9DQ4CRvik5WQ1Qy6HTO5+/6ADXA/aFukVie

  rG75K4mLh706ZWYnlBu6GQ6M7DZb5Qyo0MzzU9pTrJGjZinELACVxFkCgYEA5IFY

  HcGd9w/GI17WD2Es1quZ8HqcBFX8exwrOxMRluQXPOvdkxXrdmTDepeJnjDdFZtI

  v4slJmsTSh2v/eq82T5QWb7lIdYdePs8eZv3af6NBHwBxrEshuYYvXAuIFCbWhXk

  Rc/G5eSZNa4x/amdRoTkLrc6AXi9YB00eIRhO1ECgYEAnHTI9hFtzQB9MGeFUmQL

  pUCliCVm1ut7C2C5zxTqdfmIinU+BZzDS0II/VpU4kNIApFNbcAtJUHEXvZvesww

  xWgyzExIL9NWUq0EuklBCBbXqVuwGVgQqcVW3YHXUrL5d/lzA2GaMrIJL7jAObvR

  Acg2TDRBPj9Xu+Me6BJjvZkCgYEA2fVGR5vXQUIajMJ5DFJ0oo8sVuWcy8X4/rTv

  x3l43aTTRZj10ManwlZ63wSMkAer2mA0FAB1fx/DVn7a0CiH2fBGVFRx2sSReESs

  epL6fHABsrVWPF/jSQlRr+DBHrHEfTlEdBKsdbyHJ1zw8jRHgGxh+u1qttykRnmV

  Ax/CXwECgYEAhBeTTguO9CCikxWYUT1ax+4jdBKu9vg3AfCjivW8IcI/6XpBQeAJ

  q9weIvpLMUDrgEnly3p/AeqZ2QoKJUU9h9XIUQ+oFOAZT0WHHcqiOjoKEI/mO2oY

  8TYaWbBSAj9SeGWomkE0fYF5QNSL2YVgXx+WNLoEUg9x6kARWyfgmCU=

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.overhang.io
LOCAL_PROJECT_NAME: Project-Occa
MYSQL_ROOT_PASSWORD: MWfwsrpw
OPENEDX_MYSQL_PASSWORD: NSq27DD1
OPENEDX_SECRET_KEY: Y4D2Ad9PNxh6vdOatXmUlEyj
PLATFORM_NAME: My Open edX
PLUGINS:
- mfe
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
